# -*- coding: utf-8 -*-
"""Hacktoberfest3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQXTZbkxHU5UxttzVm7ai9J58kES50sg
"""

#Q)Write a python program to calculate the sum of all the numbers within a range.
l=int(input("Enter lower bound of range:"))
u=int(input("Enter upper bound of range:"))
sum=0
i=0
for i in range(l,u+1):
  sum=sum+i
  i+=1
print("Sum is:",sum)